---
title: "data preprocessing"
author: "Joshua Gichana"
date: "2022-12-07"
output: html_document
---
```{r}
library(readr)
Dataset <- read_csv('Dataset.csv')
```

#checking missing values

```{r}
any(is.na(Dataset))
sum(is.na(Dataset))
```

#imputing the missing values
```{r}
Dataset$Age <- ifelse(is.na(Dataset$Age),ave(Dataset$Age,FUN=function(x)mean(x,na.rm=TRUE)),Dataset$Age)
Dataset$Salary <- ifelse(is.na(Dataset$Salary),ave(Dataset$Salary,FUN=function(x)mean(x,na.rm=TRUE)),Dataset$Salary)
```

#encoding categorical data
```{r}
Dataset$Country <- factor(Dataset$Country,levels=c('France','Spain','Germany'),labels=c(1.0,2.0,3.0))
Dataset$Purchased <- factor(Dataset$Purchased,levels=c('No','Yes'),labels=c(0,1))
Dataset$Purchased[is.na(Dataset$Purchased)] <- 0
as.factor(Dataset$Purchased)
```

#splitting the data
```{r}
library(caTools)
set.seed(123)
split=sample.split(Dataset$Purchased,SplitRatio=4/5)
training_set=subset(Dataset,split==TRUE)
test_set=subset(Dataset,split==FALSE)
training_set
test_set
```

#feature scaling
```{r}
training_set[,2:3] <- scale(training_set[,2:3])
test_set[,2:3] <- scale(test_set[,2:3])
training_set
test_set
```

